FROM alpine:latest

WORKDIR /app

RUN apk update && \
    apk add --upgrade apk-tools && \
    apk upgrade --available && \
    apk add bash clang-extra-tools python3 py3-pip py3-virtualenv && \
    clang-format --version && \
    python3 -m venv /app/venv && \
    . /app/venv/bin/activate && \
    pip install --upgrade pip && \
    pip install black && \
    apk add --upgrade shfmt

COPY . .

CMD ["./formatter.sh"]
