FROM python:3.8

WORKDIR .

COPY requirements.txt .

RUN pip3 install --no-cache-dir -r requirements.txt
RUN apt update && apt install -y bc

# ソースコードをコピー
COPY . .

CMD ["/bin/bash", "./run_ptest.sh"]
