FROM alpine:latest

WORKDIR .

RUN apk update && apk add bash

RUN apk add --no-cache clang-extra-tools && \
    clang-format --version

RUN apk add --update python3 py3-pip && rm /usr/lib/python3.11/EXTERNALLY-MANAGED && \
    apk add --no-cache python3 py3-pip && \
    pip install --upgrade pip && \
    pip3 install black

RUN apk add --upgrade shfmt

COPY . .

CMD ["./formatter.sh"]