; HTTPメッセージの定義
HTTP-message = request-line *( field-line CRLF ) [ message-body ]

; HTTPのリクエストライン
request-line = method SP request-target SP HTTP-version CRLF

; リクエストターゲットの定義
request-target = origin-form = absolute-path [ "?" query ]

; 絶対パスとクエリの定義
absolute-path = 1*("/" segment)
segment = *pchar
query = *( pchar / "/" / "?" )

; パーセントエンコーディングされた文字、予約されていない文字、およびサブデリミタの定義
pchar = unreserved / pct-encoded / sub-delims / ":" / "@"
unreserved = ALPHA / DIGIT / "-" / "." / "_" / "~"
pct-encoded = "%" HEXDIG HEXDIG
sub-delims = "!" / "$" / "&" / "'" / "(" / ")"
            / "*" / "+" / "," / ";" / "="

; HTTPバージョンの定義
HTTP-name = %x49.54.54.50 ; "HTTP"
HTTP-version = HTTP-name "/" DIGIT "." DIGIT

; ヘッダーフィールドの定義
field-line = field-name ":" OWS field-value OWS
field-name = token
field-value = *( field-content )
field-content = field-vchar [ 1*( SP / HTAB ) field-vchar ]
field-vchar = VCHAR

; トークンの定義
token = 1*tchar
tchar = "!" / "#" / "$" / "%" / "&" / "'" / "*"
       / "+" / "-" / "." / "^" / "_" / "`" / "|" / "~"
       / DIGIT / ALPHA

; メソッドの制限
method = "GET" / "HEAD" / "POST" / "DELETE"

; メッセージ本体の定義
message-body = *OCTET
OCTET = any 8-bit sequence of data 

; オプショナルな空白
OWS = *( SP / HTAB )

; 基本的な定義
HEXDIG = DIGIT / "A" / "B" / "C" / "D" / "E" / "F" / "a" / "b" / "c" / "d" / "e" / "f"
ALPHA =  %x41-5A / %x61-7A  ; A-Z / a-z
VCHAR = %x00-7F / %x00-1F / %x7F / %x20-7E / %x30-39 / %x41-5A / %x61-7A / %x20-2F / %x3A-40 / %x5B-60 / %x7B-7E  ; any visible [USASCII] character

; インターネット標準の改行
CRLF = CR LF
CR = %x0D  ; carriage return
LF = %x0A  ; linefeed

