; basic rules
ALPHA	= "A" / "B" / "C" / "D" / "E" / "F" / "G" / "H" / "I" / "J" / "K" / "L" / "M" / "N" / "O" / "P" / "Q" / "R" / "S" / "T" / "U" / "V" / "W" / "X" / "Y" / "Z"
alpha = "a" / "b" / "c" / "d" / "e" / "f" / "g" / "h" / "i" / "j" / "k" / "l" / "m" / "n" / "o" / "p" / "q" / "r" / "s" / "t" / "u" / "v" / "w" / "x" / "y" / "z"
VCHAR	= %x21-7E ; visible (printing) characters
VCHAR-IN-PATH	= (VCHAR - "/") ; VCHARから"/"を除く
DIGIT	= "0" / "1" / "2" / "3" / "4" / "5" / "6" / "7" / "8" / "9"
hexdig = DIGIT / "A" / "B" / "C" / "D" / "E" / "F" / "a" / "b" / "c" / "d" / "e" / "f"
WS	= " " / "\t" / NEWLINE ;スペース、水平タブまたは改行
OWS	= *(WS) ;optional ws
h16 = 1*4HEXDIG
NEWLINE	= "\n"
alphadigit = ALPHA / alpha / DIGIT ;アルファベットまたは数字
status	= 3(DIGIT)
END_DIRECTIVE	= ";"

absolute-path	= "/" *(path-segment)
path-segment	= 1*( VCHAR-IN-PATH ) ["/"]
uri	= absolute-path ;表記は同じだが、uriはrootの後に追加される root/uri
path	= absolute-path / uri 
file	= uri

time-sec	= DIGIT ["s"]
url	= scheme "://" host
scheme	= "http" / "https";
host	= VCHAR

ip-address	= ip-address "/" "0"-"32"
on-off	= "ON" / "OFF"
method	= "GET" / "HEAD" / "PUT" / "DELETE" ;Allowing the GET method makes the HEAD method also allowed

;ip rules
ip-address = IPv4-address / IPv6-address
IPv4-address = dec-octet "." dec-octet "." dec-octet "." dec-octet
dec-octet = DIGIT / "1"-"9" DIGIT / "1" DIGIT DIGIT / "2" "0"-"4" DIGIT / "25" "0"-"5" ; 0~255
IPv6-address	= 6( h16 ":" ) ls32
			/ "::" 5( h16 ":" ) ls32
			/ [               h16 ] "::" 4( h16 ":" ) ls32
			/ [ *1( h16 ":" ) h16 ] "::" 3( h16 ":" ) ls32
			/ [ *2( h16 ":" ) h16 ] "::" 2( h16 ":" ) ls32
			/ [ *3( h16 ":" ) h16 ] "::"    h16 ":"   ls32
			/ [ *4( h16 ":" ) h16 ] "::"              ls32
			/ [ *5( h16 ":" ) h16 ] "::"              h16
			/ [ *6( h16 ":" ) h16 ] "::"

ls32	= ( h16 ":" h16 ) / IPv4address ;()はグループを示すので、右を期待する→ 16進数:16進数
h16 = 1*4(HEXDIG) ;HEXDIGが1回から4回まで続く
IPv4-subnetmask	= 0-32
IPv6-prefix	= 0-128

; syntax definition
main-context	= [ *(OWS) http-context *(OWS)] [*(OWS) errorlog-directive *(OWS)]
http-context	= 1("http" OWS "{" OWS *(server-context) OWS "}") ;webサーバ全体の設定
errorlog-directive	= "error_log" WS file [WS level] OWS END_DIRECTIVE ;Default: logs/error.log error
level	= "debug" / "info" / "notice" / "warn" / "error" / "crit" / "alert" / "emerg" ;指定したlevel以上を出力する

server-context	= "server" OWS "{" OWS *(serverconfig) OWS "}" ;{}の中が空も許容する
serverconfig	= [listen-directive] [server-name-directive] [location-directive]

listen-directive	= "listen" WS address-port OWS END_DIRECTIVE
address-port	= address [ ":" port ] / port ;デフォルトaddress:0.0.0.0 デフォルトport:80
address	=  "*" / "localhost" / ip-address
port	= 1*(DIGIT)  ;少なくとも1回のDIGITが続くシーケンス

server-name-directive	= "server_name" 1*(WS VCHAR) OWS END_DIRECTIVE ; The first name becomes the primary server name

location-directive	= "location" WS uri "{" OWS *[location-config] OWS "}"
location-config	= root-directive
				/ keepalive-timeout-directive
				/ error-page-directive 
				/ return-directive
				/ limit-except-directive
				/ permission-directive
				/ display-dir-list-directive
				/ index-file-directive
				/ client-max-body-size-directive


root-directive	= "root" WS absolute-path OWS END_DIRECTIVE
send-timeout	= "send_timeout" WS time-sec ;Default: 60s
keepalive-timeout-directive	= "keepalive_timeout" time-sec OWS END_DIRECTIVE;Default: 75s

return-directive	= "return" WS status WS uri OWS END_DIRECTIVE ; redirectで使用

client-max-body-size-directive	= "client_max_body_size" WS size-mb OWS END_DIRECTIVE ;Default:1m, size to 0 disables checking of client size-mb	= DIGIT ["m"] ; megabytes

error-page-directive	= "error_page" WS error-codes ["=" status] WS uri OWS END_DIRECTIVE
error-codes = error-code *(SP error-code)
error-code	= status

permission-directive	= permission WS permission-target OWS END_DIRECTIVE
permission-target	= IPv4-address "/" IPv4-subnetmask / IPv6-address "/" IPv6-prefix / all 
permission	= "allow" / "deny"

limit-except-directive	= "limit_except" WS  method OWS "{" OWS *(permission-directive) OWS "}"

display-dir-list-directive	= "autoindex" WS on-off OWS END_DIRECTIVE

index-file-directive	= "index" WS 1*(file) OWS END_DIRECTIVE;リクエストがディレクトリ(/)に対するもののレスポンスを設定。複数のファイルが存在する場合左から順に探す

comment	= "#" NEWLINE ; NEWLINEまでコメントアウト