ALPHA	= "A" / "B" / "C" / "D" / "E" / "F" / "G" / "H" / "I" / "J" / "K" / "L" / "M" / "N" / "O" / "P" / "Q" / "R" / "S" / "T" / "U" / "V" / "W" / "X" / "Y" / "Z"
alpha = "a" / "b" / "c" / "d" / "e" / "f" / "g" / "h" / "i" / "j" / "k" / "l" / "m" / "n" / "o" / "p" / "q" / "r" / "s" / "t" / "u" / "v" / "w" / "x" / "y" / "z"
DIGIT	= "0" / "1" / "2" / "3" / "4" / "5" / "6" / "7" / "8" / "9"
hexdig = DIGIT / "A" / "B" / "C" / "D" / "E" / "F" / "a" / "b" / "c" / "d" / "e" / "f"
WS	= " " / "\t" / NEWLINE ;スペース、水平タブまたは改行
OWS	= *(WS) optional ws
h16 = 1*4HEXDIG
NEWLINE	= "\n"
alphadigit = ALPHA / alpha / DIGIT ;アルファベットまたは数字
END_DIRECTIVE	= ";"

http	= "http" OWS "{" OWS server-directive OWS "}" END_DIRECTIVE

server-directive	= "server" OWS "{" serverconfig "}" END_DIRECTIVE
serverconfig	= listen-directive END_DIRECTIVE

listen-directive	= "listen" WS address-port
address-port	= address [ ":" port ] / port ;デフォルトaddress:0.0.0.0 デフォルトport:80
address	=  * / localhost / IPv4-address / IPv6-address 
IPv4-address = dec-octet "." dec-octet "." dec-octet "." dec-octet
dec-octet = DIGIT / "1"-"9" DIGIT / "1" DIGIT DIGIT / "2" "0"-"4" DIGIT / "25" "0"-"5" ; 0~255
IPv6address	= 6( h16 ":" ) ls32
			/ "::" 5( h16 ":" ) ls32
			/ [               h16 ] "::" 4( h16 ":" ) ls32
			/ [ *1( h16 ":" ) h16 ] "::" 3( h16 ":" ) ls32
			/ [ *2( h16 ":" ) h16 ] "::" 2( h16 ":" ) ls32
			/ [ *3( h16 ":" ) h16 ] "::"    h16 ":"   ls32
			/ [ *4( h16 ":" ) h16 ] "::"              ls32
			/ [ *5( h16 ":" ) h16 ] "::"              h16
			/ [ *6( h16 ":" ) h16 ] "::"

ls32	= ( h16 ":" h16 ) / IPv4address ;()はグループを示すので、右を期待する→ 16進数:16進数
h16 = 1*4(HEXDIG) ;HEXDIGが1回から4回まで続く
port	= 1*(DIGIT)  ;少なくとも1回のDIGITが続くシーケンス

server_name	= "server_name" WS alphadigit END_DIRECTIVE

error-page-directive	= "error_page" WS error_codes [response] END_DIRECTIVE
error-codes = error-code *(SP error-code) END_DIRECTIVE
error_code	= 3(DIGIT) END_DIRECTIVE
response	= "/"  / URL

client_max_body_size_directive	= "client_body_buffer_size" OWS DIGIT END_DIRECTIVE
