ALPHA	= "A" / "B" / "C" / "D" / "E" / "F" / "G" / "H" / "I" / "J" / "K" / "L" / "M" / "N" / "O" / "P" / "Q" / "R" / "S" / "T" / "U" / "V" / "W" / "X" / "Y" / "Z"
alpha = "a" / "b" / "c" / "d" / "e" / "f" / "g" / "h" / "i" / "j" / "k" / "l" / "m" / "n" / "o" / "p" / "q" / "r" / "s" / "t" / "u" / "v" / "w" / "x" / "y" / "z"
DIGIT	= "0" / "1" / "2" / "3" / "4" / "5" / "6" / "7" / "8" / "9"
hexdig = DIGIT / "A" / "B" / "C" / "D" / "E" / "F" / "a" / "b" / "c" / "d" / "e" / "f"
WS	= " " / "\t" / NEWLINE ;スペース、水平タブまたは改行
OWS	= *(WS) ;optional ws
h16 = 1*4HEXDIG
NEWLINE	= "\n"
alphadigit = ALPHA / alpha / DIGIT ;アルファベットまたは数字
status	= 3(DIGIT)
END_DIRECTIVE	= ";"

main	= [http] [errorlog]
http	= 1("http" OWS "{" OWS server-directive OWS "}") ;webサーバ全体の設定
errorlog	= "error_log" WS path [WS level] OWS END_DIRECTIVE
level	= "debug" / "info" / "notice" / "warn" / "error" / "crit" / "alert" / "emerg" ;指定したlevel以上を出力する

server-directive	= "server" OWS "{" [serverconfig] "}" ;{}の中が空も許容する
serverconfig	= [listen-directive] [server-name] [location-directive]

listen-directive	= "listen" WS address-port
address-port	= address [ ":" port ] / port ;デフォルトaddress:0.0.0.0 デフォルトport:80
address	=  * / localhost / ip-address
ip-address = IPv4-address / IPv6-address
IPv4-address = dec-octet "." dec-octet "." dec-octet "." dec-octet
dec-octet = DIGIT / "1"-"9" DIGIT / "1" DIGIT DIGIT / "2" "0"-"4" DIGIT / "25" "0"-"5" ; 0~255
IPv6-address	= 6( h16 ":" ) ls32
			/ "::" 5( h16 ":" ) ls32
			/ [               h16 ] "::" 4( h16 ":" ) ls32
			/ [ *1( h16 ":" ) h16 ] "::" 3( h16 ":" ) ls32
			/ [ *2( h16 ":" ) h16 ] "::" 2( h16 ":" ) ls32
			/ [ *3( h16 ":" ) h16 ] "::"    h16 ":"   ls32
			/ [ *4( h16 ":" ) h16 ] "::"              ls32
			/ [ *5( h16 ":" ) h16 ] "::"              h16
			/ [ *6( h16 ":" ) h16 ] "::"

ls32	= ( h16 ":" h16 ) / IPv4address ;()はグループを示すので、右を期待する→ 16進数:16進数
h16 = 1*4(HEXDIG) ;HEXDIGが1回から4回まで続く
port	= 1*(DIGIT)  ;少なくとも1回のDIGITが続くシーケンス

server-name	= "server_name" 1*(WS alphadigit) END_DIRECTIVE ; 

location-directive	= "location" WS path "{" OWS *[location-config] OWS "}"END_DIRECTIVE
location-config	= root-directive
				/ keepalive-timeout
				/ error-page-directive 
				/ return-directive
				/ limit-except-directive
				/ permission-directive
				/ display-dir-list
				/ index-file

root-directive	= "root" WS path END_DIRECTIVE
send-timeout	= "send_timeout" WS time-sec ;Default: 60s
path	= "/" 1*(path-segment)
path-segment	= 1*(ALPHA / DIGIT / "-" / "_") ["/"]
keepalive-timeout	= "keepalive_timeout" time-sec ;Default: 75s
time-sec	= DIGIT ["s"]

return-directive	= "return" WS status WS uri OWS END_DIRECTIVE
uri	= scheme "://" host
scheme	= "http" / "https";
host	= alphadigit

client-max-body-size	= "client_max_body_size" WS size-mb END_DIRECTIVE ;Default:1m, size to 0 disables checking of client request body size-mb	= DIGIT ["m"] ; megabytes

error-page-directive	= "error_page" WS error_codes [response] END_DIRECTIVE
error-codes = error-code *(SP error-code) END_DIRECTIVE
error_code	= status END_DIRECTIVE
response	= path-to-file
path-to-file	= path alphadigit
file	= alphadigit / path-to-file

permission-directive	= permission WS permission-target END_DIRECTIVE
permission-target	= ip-address / all 
permission	= "allow" / "deny"
ip-address	= ip-address "/" "0"-"32"

limit-except-directive	= "limit_except" WS  method OWS "{" OWS *(permission-directive) OWS "}"
method	= "GET" / "HEAD" / "PUT" / "DELETE" ;Allowing the GET method makes the HEAD method also allowed

display-dir-list	= "autoindex" WS on-off
on-off	= "ON" / "OFF"

index-file	= "index" WS 1*(file) ;リクエストがディレクトリ(/)に対するもののレスポンスを設定。複数のファイルが存在する場合左から順に探す

client_max_body_size_directive	= "client_body_buffer_size" OWS DIGIT END_DIRECTIVE
