name: Format C++ Code

on:
  pull_request:
    types: [closed]

jobs:
  format_code:
    runs-on: ubuntu-latest

    if: github.event.pull_request.merged == true
    
    permissions:
      contents: write

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Install clang-format
      run: sudo apt-get install -y clang-format

    - name: Format C++ code
      run: |
        make format
    - name: Check for changes
      id: format-changes
      run: |
        git diff --exit-code
        if [ $? -eq 0 ]; then
          echo "CHANGED=false" >> "$GITHUB_OUTPUT"
        else
          echo "CHANGED=true" >> "$GITHUB_OUTPUT"
        fi

    - name: Commit and push changes
      if: steps.format-changes.outputs.CHANGED == 'true'
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: ":recycle: auto-format c++ code"

