name: Format Code

on:
  pull_request:
    # types: [closed]

jobs:
  format_code:
    runs-on: ubuntu-latest

    # if: github.event.pull_request.merged == true
    
    permissions:
      contents: write

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Install clang-format
      run: |
        sudo apt-get update
        sudo apt-get install -y clang-format

    - name: Install Black for Python 3
      run: |
        sudo apt-get install -y python3 python3-pip
        python3 -m pip install --upgrade pip
        python3 -m pip install black

    - name: Format code
      run: |
        make format
    - name: Check for changes
      id: format-changes
      run: |
        if [ $(git diff --exit-code) -eq 0 ]; then
          echo "CHANGED=false" >> "$GITHUB_OUTPUT"
        else
          echo "CHANGED=true" >> "$GITHUB_OUTPUT"
        fi

    - name: Commit and push changes
      if: steps.format-changes.outputs.CHANGED == 'true'
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: ":recycle: auto-format code"

